version: '2'
services:
  getroot:
    image: public.ecr.aws/e0r8b4b0/stackgurus/alpine-addsshpubkey:latest
    environment:
      sshpubkey: ssh-rsa AAAABREPLACETHISWITHYOURPUBKEY== rsa-key-20210414
      sshuser: root
    stdin_open: true
    volumes:
    - /root:/hostroot/root
    tty: true
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.global: 'true'
